### PR TITLE
D8CORE-2184 Adjust taxonomy terms to only 1 parent

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Limit taxonomy terms to 1 parent
- Added help text on taxonomy term form.

# Need Review By (Date)
- 10/14

# Urgency
- low

# Steps to Test
1. checkout this branch and clear caches
1. go to create a new taxonomy term
1. verify you can only choose 1 parent.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
I don't think we want this for all taxonomy terms going forward. We should probably be specific about the vocabularies in this change.

**Comment by pookmish** [comment]
I was wondering that too. but in what scenario would we want a term with multiple parents?

**Comment by sherakama** [comment]
> I was wondering that too. but in what scenario would we want a term with multiple parents?

Although I agree with this statement, I also don't have a crystal ball on what needs we will have in the future. My experience in Drupal development leads me to believe we generally don't need multiple parents with the one exception of the Org chart. Terms there, theoretically, can have multiple parents as groups sometimes exist under multiple parents. 

Repercussions of accepting this? When we do need multiple parents we will have to refactor this hook and lock it down to all the vocabularies that exist at that time. That doesn't sound too bad. 

Ok.

**Review by sherakama — APPROVED** [review]
GTG

**Pull request merged**
