### PR TITLE
BOT-8: Add intranet state to allow file uploads

### PR DESCRIPTION
**Pull request by joegl**
# READY FOR REVIEW

# Summary
- Added `stanford_intranet.allow_file_uploads` state and functionality
- Tests are being written separately into https://github.com/SU-SWS/trustee_profile/blob/0fed57f2ba8fcf99988f2ab44f2fe245ab4dc27e/tests/codeception/acceptance/Users/IntranetCest.php#L139-L147

# Review By (Date)
- ASAP

# Criticality
6-7

# Urgency
High-ish

# Review Tasks

## Setup tasks and/or behavior to test

1. Pull and setup locally
2. Try to add a file at `media/add/file` (should see Access Denied)
3. Enable `allow_file_uploads` state: 
   * `drush sset stanford_intranet.allow_file_uploads 1`
   * `drush @<site_alias> cr`
4. Reload and try to add a file at `media/add/file` (should be able to upload a file now)
5. Disable `allow_file_uploads` state: 
   * `drush sset stanford_intranet.allow_file_uploads 0`
   * `drush @<site_alias> cr`
6. Reload and try to add a file at `media/add/file` (should see Access Denied)
7. Review `README.md` added.

### Site Configuration Sync

- Is there a config:export in this PR that changes the config sync directory? **No**

## Front End Validation
- [ ] Design is approved by @ user?
- [ ] HTML validation: Is the markup using the appropriate semantic tags and [passes validation](https://validator.w3.org/nu/)? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Cross-browser testing: Has been performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Automated accessibility: Scans performed? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?
- [ ] Manual accessibility: Manually tested? Or, [QA request ticket created](https://github.com/SU-SWS/template_warehouse/blob/master/jira_templates/QA_request_template.txt)?

### Code
- [ ] Are the naming conventions following our standards?
- [ ] Does the code have sufficient inline comments?
- [ ] Is there anything in this code that would be hidden or hard to discover through the UI?
- [ ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ ] Are tests provided? eg (unit, behat, or codeception)

### Code security
- [ ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ ] Any obvious [security flaws or new areas for attack](https://www.drupal.org/docs/8/security)?

## General
- [ ] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [ ] Is the approach to the problem appropriate?

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket(s)
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# Resources
- [AMP Tool](https://stanford.levelaccess.net/index.php)
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing)
- [HTML Validator](https://validator.w3.org/)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

### CODE REVIEW

**Comment by joegl** [comment]
@pookmish I am going to attempt to modify the test in the `trustee_profile` for this: https://github.com/SU-SWS/trustee_profile/blob/0fed57f2ba8fcf99988f2ab44f2fe245ab4dc27e/tests/codeception/acceptance/Users/IntranetCest.php#L139-L147

Are there any other places I should put tests?

**Comment by pookmish** [comment]
> Are there any other places I should put tests?

In the stanford_profile would be best. The trustees_profile can consume the commit after it gets into stanford_profile

**Comment by mdyoung3** [comment]
Worked for me.

**Comment by joegl** [comment]
@pookmish Would you mind taking a look at this quick?

@mdyoung3 It looks like the approval didn't go through.

**Review by pookmish — APPROVED** [review]
Simple enough. Thanks for the README notes.

**Pull request merged**
