### PR TITLE
D8CORE-2899: removing the character limits on the wysiwyg text field

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW
- This is for 1.5.1. It was posted early so @katrialesser can review for impact in her projects.

# Summary
- Removing the character limits on the wysiwyg text field. We want them to widen up to 100 

# Needed By (Date)
- For 1.5.1. 
- Needs review from the other subtheme teams.

# Urgency
- High

# Steps to Test

1. Pull in this branch and the one on [Stanford Basic](https://github.com/SU-SWS/stanford_basic/compare/D8CORE-2899-v2?expand=1).
2. Refresh everything.
3. Make new text areas and add content with the wysiwyg editor. Verify the character limit is 100.
4. Test on several different page types.

# Affected Projects or Products
- Basic, Adapt, SOE

# Associated Issues and/or People
- D8CORE-2899
- https://github.com/SU-SWS/stanford_basic/compare/D8CORE-2899-v2?expand=1
- The Jira ticket has all the classes changed listed out.
- @katrialesser @rmundstock @cjwest 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by cjwest — APPROVED** [review]
@jenbreese,
I found the [conversation in Slack](https://stanfordwebservices.slack.com/archives/GJQJ7HTK7/p1604085347288100). 
My only concern was that Kerri and Shea were aware of this change.

**Comment by cjwest** [comment]
@jenbreese, 
I see that this is not marked "Ready for review." I see that there's be discussion about this and I'm fine with the changes.

**Review by sherakama — APPROVED** [review]
I'm good with this.

**Comment by jenbreese** [comment]
@cjwest Can you merge this one? It goes along with the other one you merged. Thank you!

**Comment by cjwest** [comment]
Looks good to me!

Before:
linelength-before-localhost_32793-2020 12 01-18_32_29

After:

**Pull request merged**
