### PR TITLE
D8CORE-2856 Remove unwanted views from the list paragraph type

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Limit view options in the react widget.

see https://github.com/SU-SWS/stanford_profile/pull/310

### CODE REVIEW

**Comment by sherakama** [comment]
As the paragraph type could technically be used without the react UI shouldn't you also limit the options on the regular widget?

**Comment by pookmish** [comment]
Meh, I'm not very concerned about that. We are explicit with which paragraph types are allowed in the other content types right now. And those views technically still work. Just might not display as expected at this time, so I'm reducing scope for follow up after this.

**Comment by sherakama** [comment]
Aye, but you will forget about the fact they aren't restricted in the default UI, and somewhere down the line, someone else could implement these paragraphs on another content type not knowing what wasn't in scope. You don't need to make changes to this PR but I'm leaving this comment for an "I told you so" later.

**Comment by pookmish** [comment]
I assume this is g2g since https://github.com/SU-SWS/stanford_profile/pull/310 is g2g?

**Pull request merged**
