### PR TITLE
D8CORE-3516: fixing the missing arrow icon

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Fixing where webpack puts the images

# Needed By (Date)
- 2/23

# Urgency
- Med

# Steps to Test

1. Add this change
2. run `npm run publish` to get webpack to rebuild the dist directories. 
3. Add a header in the WYSIWYG text field.
4. Verify you get the right facing arrow in the editor and on the page.

# Affected Projects or Products
- SOE
- Stanford Basic

# Associated Issues and/or People
- D8CORE-3516
- @katrialesser - any impact for you?

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by imonroe** [comment]
@jenbreese -- does this fix the issue in https://stanfordits.atlassian.net/browse/D8CORE-3424 ?  If so, I'll note it in that ticket as well....

**Review by imonroe — APPROVED** [review]
looks good

**Comment by jenbreese** [comment]
@imonroe Yes, it should fix that too. I'm in a funny build state so can you try it to confirm?

**Comment by imonroe** [comment]
@jenbreese confirmed.  this looks good.

**Pull request merged**
