### PR TITLE
D8CORE-2201, D8CORE-2448: hiding the default external link

### PR DESCRIPTION
**Pull request by cjwest**
# READY FOR REVIEW

# Summary
When we add the extlink module, it applies the external `<svg>` to _all_ external links. This PR visually hides it so we can use our own styles. This keeps the screen reader text "link is external" thus helping to keep our links accessible. 

This also styles the External Link's existing mailto icon.

# Needed By (Date)
- Soon

# Urgency
- not urgent

# Steps to Test

1. Check out this branch,
1. Clear the cache
1. Verify that the external link <svg> does not show on all links, but the aria-label "link is external" is applied to every link. 
1. Verify that the external link style shows up in WYSIWYG text fields.

Screen Shot 2020-08-06 at 5 51 27 PM

# Affected Projects or Products
- D8Core

# Associated Issues and/or People
- JIRA ticket https://stanfordits.atlassian.net/browse/D8CORE-2448
https://stanfordits.atlassian.net/browse/D8CORE-2201
https://stanfordits.atlassian.net/browse/D8CORE-2492
- Other PRs: https://github.com/SU-SWS/stanford_profile/pull/261
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
I'm not sure about this approach and have some questions. Grab a meeting with me when we are back from vacation.

**Comment by cjwest** [comment]
@sherakama, 
I tried adding the `.su-link--external` class and hilarity ensued. It removed the `.ext` class from one span, but not the other, and I couldn't find a way to style the rogue SVG. I then tried adding  `.su-link--external` class to have  both, i.e., `.ext .su-link--external`, and I couldn't limit the display just to the page-content and local-footer regions. 

What's in the PR is working. I realize there's more to do:
1. I need to break these styles out into a separate file
1. I need to test this on all the content types, paragraphs, etc.
1. I'm sure there's more 

I would like your $0.02 before I proceed.

**Comment by cjwest** [comment]
Hilarity looks like this:

Screen Shot 2020-08-11 at 7 22 17 PM

**Comment by cjwest** [comment]
Here's how it looks with the current config:

Screen Shot 2020-08-11 at 7 29 22 PM


Screen Shot 2020-08-11 at 7 29 15 PM

**Comment by sherakama** [comment]
Can you export your configuration into this module or provide a companion PR in the stanford_profile module as well as add the dependency to composer.json please.

**Comment by sherakama** [comment]
> Can you export your configuration into this module or provide a companion PR in the stanford_profile module as well as add the dependency to composer.json please.

Oh, I see it here: https://github.com/SU-SWS/stanford_profile/pull/261

**Comment by cjwest** [comment]
@sherakama,
I think I found my mistake.

**Comment by cjwest** [comment]
This is ready to review:

screenshot-localhost_32772-2020 08 13-12_19_41

**Comment by cjwest** [comment]
@ishahism,
Thanks for your help on this!

Screen Shot 2020-08-13 at 3 55 07 PM

**Comment by cjwest** [comment]
@ishahism,

I updated the button styling so it wasn't blue. We can revisit this later per Sara's instructions to address unexpected behaviours with subsequent tickets. 

Screen Shot 2020-08-13 at 5 10 31 PM

**Comment by cjwest** [comment]
@sherakama,

Looks like the underlines disappeared with the merge. 
I created a subsequent ticket to address it.

https://stanfordits.atlassian.net/browse/D8CORE-2533

Screen Shot 2020-08-14 at 4 00 08 PM

**Pull request merged**
