### PR TITLE
Update hook and drush command to move all public files into private file system.

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Update hook and drush commands to move all public files into private directories.

# Need Review By (Date)
- asap

# Urgency
- high

# Steps to Test
1. checkout this branch
2. enable intranet `drush sset stanford_intranet 1`
3. run database updates `drush updb` or `drush stanford-intranet:move-files` to run just the file movements
4. view any media and validate the file/image exists in the private directory.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by imonroe — APPROVED** [review]
This works as described.  I found when I ran it locally, it left some images in the public directory, but I realized after checking them it was images I had uploaded in an earlier iteration of the local site, which didn't have entries in the media library, so drupal wasn't aware of them.  That should be fine, since that'll never happen on production sites.

**Comment by joegl** [comment]
@pookmish @imonroe I'm looking at this PR for `cardinal_service_profile` now: https://github.com/SU-HKKU/cardinal_service_profile/pull/251 which includes this update, and am getting fatal errors:

```
In ProcessBase.php line 171:

  Unable to decode output into JSON: Syntax error

  Error: Call to a member function getPattern() on null in stanford_profile_h
  elper_post_update_8102() (line 149 of /home/joegl/apache_www/ace-gryphon/do
  croot/modules/custom/stanford_profile_helper/stanford_profile_helper.post_u
  pdate.php).
```

**Comment by joegl** [comment]
@pookmish I'm getting some really odd behavior on the update hook to move the files. What I've noticed is:

1. The original public file gets moved to the `://private` directory successfully.
2. The original public file, now in the private folder, always shows an "Access Denied" when I try to access it through the private URL.
3. A duplicate get file is getting made in the `://private` directory from the original public file (usually `<filename>_0`). 
4. The duplicate file is accessible through the private URL.

**Comment by pookmish** [comment]
I'm thinking you have file issues.

**Comment by pookmish** [comment]
Also, you should always get an access denied when trying to view the private url. The file goes through `system/file` so Drupal can managed the access.

**Comment by joegl** [comment]
> I'm thinking you have file issues.

The same exact thing happened to me on Acquia dev environment last week when I was attempting to move files manually with SSH and drush SQL commands.

**Comment by joegl** [comment]
It also should be noted both times I experienced this (local and on Acquia) has been with the Trustees sites (so `ace-botgryphon` and `trustee_profile` combo).

**Comment by joegl** [comment]
> Also, you should always get an access denied when trying to view the private url. The file goes through `system/file` so Drupal can managed the access.

Yea, by private URL I meant the `system/file` URL.

**Comment by joegl** [comment]
Ha thanks for cleaning that up. As a follow-up comment, the behavior I described wasn't related to this and everything works as designed.

**Pull request merged**
