### PR TITLE
D8CORE-3345 Update hook to update paths for terms and content.

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Update hook for path auto changes https://github.com/SU-SWS/stanford_profile/pull/505

# Need Review By (Date)
- 3/15

# Urgency
- medium

# Steps to Test
1. follow steps in https://github.com/SU-SWS/stanford_profile/pull/505

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by imonroe** [comment]
Will this break inbound links?  Should we set up redirects for the old patterns to the new ones?

I am strongly in favor of changing the pathauto settings, and I very much agree with the new paths.  I am a little concerned though that this is going to affect SEO on large sites.  I'm also a little worried that this is going to mess up the Engineering main site, where we have deliberately changed the news paths to account for their Magazine section.

**Comment by pookmish** [comment]
> Will this break inbound links? Should we set up redirects for the old patterns to the new ones?

When re-saving, the redirects are automatically created.

**Comment by pookmish** [comment]
> I'm also a little worried that this is going to mess up the Engineering main site, where we have deliberately changed the news paths to account for their Magazine section.

I would expect there to be tests in SOE for that. resaving won't change their paths for that, only clear caches

**Comment by joegl** [comment]
@pookmish @imonroe I'm looking at this PR for `cardinal_service_profile` now: https://github.com/SU-HKKU/cardinal_service_profile/pull/251 which includes this update, and am getting fatal errors:

```
In ProcessBase.php line 171:

  Unable to decode output into JSON: Syntax error

  Error: Call to a member function getPattern() on null in stanford_profile_h
  elper_post_update_8102() (line 149 of /home/joegl/apache_www/ace-gryphon/do
  croot/modules/custom/stanford_profile_helper/stanford_profile_helper.post_u
  pdate.php).
```

**Comment by joegl** [comment]
> 

This worked as a workaround for me for now: https://github.com/SU-SWS/stanford_profile_helper/pull/205

**Pull request merged**
