### PR TITLE
CSD-227 Preprocess breadcrumbs to add the current page

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- https://github.com/SU-SWS/stanford_profile/pull/254
- Adds the current page title to the end of the breadcrumbs, only for the main theme and only if config pages is enabled to display them.

# Need Review By (Date)
- 7/22

# Urgency
- low

# Steps to Test
Follow steps in https://github.com/SU-SWS/stanford_profile/pull/254

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
Breadcrumbs? Who thought that was a good idea?

**Comment by pookmish** [comment]
Nica for the CS project. But also Sara https://stanfordits.atlassian.net/browse/D8CORE-993

**Comment by sherakama** [comment]
I like breadcrumbs as much as John likes FAQs and Word Clouds.

**Comment by jbickar** [comment]
_I_ like breadcrumbs as much as I like FAQs and word clouds.

**Comment by sherakama** [comment]
Review target for release 1.3.2

**Comment by sherakama** [comment]
Sent invite for meeting 07/24

**Comment by sherakama** [comment]
The resulting discussion was to build out this functionality for core but to have it disabled by default where site owners could turn it on. Work has to be done on the behavior and placement of the breadcrumbs on the dynamic content types before it can be included everywhere.

**Comment by jbickar** [comment]
> The resulting discussion was to build out this functionality for core but to have it disabled by default where site owners could turn it on. Work has to be done on the behavior and placement of the breadcrumbs on the dynamic content types before it can be included everywhere.

So you lost, @sherakama ?

**Pull request closed without merging**
