### PR TITLE
D8CORE-2570 Update hook to create the intro blocks

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Update hook for https://github.com/SU-SWS/stanford_profile/pull/324

# Need Review By (Date)
- same time as https://github.com/SU-SWS/stanford_profile/pull/324

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Review by sherakama — APPROVED** [review]
GTG. Wow. First Update hook.

**Comment by sherakama** [comment]
Is this not in the profile in order to avoid having to port it to SOE?

**Comment by pookmish** [comment]
> Is this not in the profile in order to avoid having to port it to SOE?

Yeah. less work we gotta do later.

**Comment by pookmish** [comment]
also allows easy porting for cardinal service profile.

**Pull request merged**
