### PR TITLE
D8CORE-2420: Rebuild router on taxonomy change to fix bug with taxonomy_menu

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

# Summary
- Rebuilds router on taxonomy menu update in order to fix issue with taxonomy_menu

# Needed By (Date)
- Sept 3rd

# Urgency
- Medium high. It is a pretty bad bug.

# Steps to Test

1. On a fresh build of cardinalsites edit the person types move a nested menu item to the top level (/admin/structure/taxonomy/manage/stanford_person_types/overview)
2. Review /people to see nested item now in filter menu
3. Move item back under another so that it is now nested
4. Review /people and see item still in filter menu 
5. Check out this branch
6. Repeat steps 1 - 4 but now the item should no longer be in the filter menu.

# Affected Projects or Products
- D8CORE
- Lots of sites and reports

# Associated Issues and/or People
- D8CORE-2420

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by pookmish** [comment]
Its not a cache issue?

**Comment by sherakama** [comment]
I had the same results as the people in the following thread:
* https://www.drupal.org/project/taxonomy_menu/issues/2867626

**Comment by sherakama** [comment]
I haven't been able to dig into this as much as I would have liked to. 

There are other issues as well, like the sorting, that are a problem. A couple options forward... 

1. Merge this and continue to revisit in the next release
2. Hold and fix all the things

I am leaning towards option 1 as there isn't a workaround for site_managers to resolve a stuck menu item. I can keep the ticket in the backlog for the next sprint.

**Comment by pookmish** [comment]
I'm good with the approach in option 1.

**Pull request merged**
