### PR TITLE
D8CORE-2951 D8CORE-2952 Style adjustments for people cards

### PR DESCRIPTION
**Pull request by pookmish**
# READY FOR REVIEW

# Summary
- Adjusted styles for person cards with a single per row
- limit person image to 300px.

# Need Review By (Date)
- asap

# Urgency
- high.

# Steps to Test
1. checkout this branch
1. clear browser cache
1. create page with a person content reference as the only 1 per row.
1. verify the card is horizontal.

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by jenbreese** [comment]
@pookmish Is this what you are expecting? It seems wide to me so I thought I'd check. 
Screen Shot 2020-11-05 at 3 46 48 PM

**Comment by pookmish** [comment]
Yep. that's the expected behavior. see the mockups at https://www.figma.com/file/TFGD5bi9yYxvEfmTdVF56E/SWS-D8-Person-WF-%2B-Mocks?node-id=1266%3A10935

**Comment by jenbreese** [comment]
I'm not getting any content for my card and the person does have content in the fields. 
Screen Shot 2020-11-05 at 3 57 12 PM

**Comment by pookmish** [comment]
Yes there are only the name, short title and image at this time for the card display.

**Review by jenbreese — APPROVED** [review]
Works fine for me.

**Pull request merged**
