### PR TITLE
D8CORE-2130: Updates to the Cta list paragraph

### PR DESCRIPTION
**Pull request by jenbreese**
# READY FOR REVIEW

# Summary
- Updates to the Cta list paragraph

# Needed By (Date)
- Tuesday, 7th

# Urgency
- Med

# Steps to Test

1. Pull in this branch and the linked request below.
2. Verify when adding a CTA List or a story, the widths are limited like we do for the card.

# Affected Projects or Products
- SOE subtheming
- CTA List paragraph

# Associated Issues and/or People
-  D8CORE-2130
- https://github.com/SU-SOE/soe_basic/pull/8

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by imonroe** [comment]
So, I don't have a way to test this yet, since the soe_paragraphs are in the soe_profile, but not in the stanford_profile.  As of now, the stanford_profile_helper module isn't in the soe_profile, so ... yeah, I don't have a way to test.  The changes seem uncontroversial though.

**Comment by sherakama** [comment]
The submodules were abstracted to another project https://github.com/SU-SWS/stanford_profile_helper.

Please move these changes into that module.

**Comment by imonroe** [comment]
> The submodules were abstracted to another project https://github.com/SU-SWS/stanford_profile_helper.
> 
> Please move these changes into that module.

that sort of means we're starting to casually move `soe_paragraphs` into `stanford_profile`, as well as just `soe_profile`.  Is that the desired outcome?

**Comment by jenbreese** [comment]
@sherakama and @imonroe Is it ok to move tomorrow?

**Comment by imonroe** [comment]
Ok, so per @sherakama these changes should be in the stanford_profile_helper, which is in fact the case.  Now that this repo is integrated into the soe_profile, I am able to test these changes.  Pulled them down on my local, and they work as described. (and they look pretty nice, too.)  I'm good with this PR, as long as @sherakama isn't asking for a change that I don't understand.

**Pull request merged**
